language: go
go_import_path: github.com/maxatome/go-testdeep

sudo: false

matrix:
  include:
    - go: 1.9.x
    - go: 1.10.x
    - go: 1.11.x
    - go: 1.12.x
      env:
        - GO_TEST_SAFE_FLAGS="-covermode=atomic -coverprofile=coverage-safe.out ./..."
        - GO_TEST_UNSAFE_FLAGS="-covermode=atomic -coverprofile=coverage-unsafe.out ./..."
        - USE_LINTER=1
      install:
        - >
          version=1.15.0; name=golangci-lint-$version-linux-amd64;
          wget -q -O - https://github.com/golangci/golangci-lint/releases/download/v$version/$name.tar.gz |
            tar -zxvf - -C $GOPATH/bin &&
              mv $GOPATH/bin/$name/golangci-lint $GOPATH/bin
      after_success:
        - go get github.com/mattn/goveralls
        - go get github.com/wadey/gocovmerge
        - gocovmerge coverage-safe.out coverage-unsafe.out > coverage.out
        - goveralls -coverprofile=coverage.out -service=travis-ci
    - go: master
  allow_failures:
    - go: master
  fast_finish: true

script:
  - export GORACE="halt_on_error=1"
  - go get -t ./...
  - go test -race -tags safe $GO_TEST_SAFE_FLAGS ./...
  - go test -race $GO_TEST_UNSAFE_FLAGS ./...
  - >
    [ "$USE_LINTER" != 1 ] ||
      golangci-lint run -E gofmt -E golint -E maligned -E misspell -E prealloc -E unconvert ./...
