name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    env:
      GO_CURRENT: 1.15.x

    strategy:
      matrix:
        go-version: [1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, tip]
        full-tests: [false]
        include:
          - go-version: 1.16.x
            full-tests: true

    runs-on: ubuntu-latest

    steps:
      - name: Setup go
        run: |
          curl -sL https://raw.githubusercontent.com/maxatome/install-go/v2.1/install-go.pl |
              perl - ${{ matrix.go-version }} $HOME/go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Linting
        if: matrix.full-tests
        run: |
          wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
              sh -s -- -b $HOME/go/bin v1.37.1
          echo $PATH
          $HOME/go/bin/golangci-lint run --max-issues-per-linter 0 \
                                         --max-same-issues 0 \
                                         -E exportloopref \
                                         -E gocritic \
                                         -E godot \
                                         -E goimports \
                                         -E golint \
                                         -E maligned \
                                         -E misspell \
                                         -E prealloc \
                                         -E unconvert \
                                         -E whitespace \
                                         ./...

      - name: Testing
        continue-on-error: ${{ matrix.go-version == 'tip' }}
        run: |
          go version
          if [ ${{ matrix.full-tests }} = true ]; then
              GO_TEST_SAFE_FLAGS="-covermode=atomic -coverprofile=coverage-safe.out"
              GO_TEST_UNSAFE_FLAGS="-covermode=atomic -coverprofile=coverage-unsafe.out"
          fi

          case ${{ matrix.go-version }} in
              1.9.x | 1.10.x) # Before go 1.11, go modules are not available
                  mkdir -p ../src/github.com/maxatome
                  ln -s $(pwd) ../src/github.com/$GITHUB_REPOSITORY
                  export GOPATH=$(dirname $(pwd))
                  cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
                  ;;
          esac

          export GORACE="halt_on_error=1"
          go get -t ./...
          go test -race -tags safe $GO_TEST_SAFE_FLAGS ./...
          go test -race $GO_TEST_UNSAFE_FLAGS ./...

      - name: Reporting
        if: matrix.full-tests
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get github.com/mattn/goveralls
          go get github.com/wadey/gocovmerge
          gocovmerge coverage-safe.out coverage-unsafe.out |
              egrep -v '^github\.com/maxatome/go-testdeep/internal/json/parser\.go:' > coverage.out
          goveralls -coverprofile=coverage.out -service=github
