name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest]
        full-tests: [false]
        include:
          - go-version: 1.15.x
            platform: ubuntu-latest
            full-tests: true

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Linting
        if: matrix.full-tests
        run: |
          mkdir /tmp/linter-bin
          wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
              sh -s -- -b /tmp/linter-bin v1.30.0
          /tmp/linter-bin/golangci-lint run -E gofmt -E golint -E maligned -E misspell -E prealloc -E unconvert -E whitespace -E goimports ./...

      - name: Testing
        run: |
          if [ ${{ matrix.full-tests }} = true ]; then
              GO_TEST_SAFE_FLAGS="-covermode=atomic -coverprofile=coverage-safe.out"
              GO_TEST_UNSAFE_FLAGS="-covermode=atomic -coverprofile=coverage-unsafe.out"
          fi
          # Before go 1.11, go modules are not available
          if [ "$(expr ${{ matrix.go-version }} : '^1\.\([0-9]\+\)')" -le 10 ]; then
              mkdir -p ../src/github.com/maxatome
              ln -s $(pwd) ../src/github.com/maxatome/go-testdeep
              export GOPATH=$(dirname $(pwd))
              cd $GOPATH/src/github.com/maxatome/go-testdeep
          fi
          export GORACE="halt_on_error=1"
          go get -t ./...
          go test -race -tags safe $GO_TEST_SAFE_FLAGS ./...
          go test -race $GO_TEST_UNSAFE_FLAGS ./...

      - name: Reporting
        if: matrix.full-tests
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get github.com/mattn/goveralls
          go get github.com/wadey/gocovmerge
          gocovmerge coverage-safe.out coverage-unsafe.out > coverage.out
          goveralls -coverprofile=coverage.out -service=github
